### ISSUE TITLE
get order from orderId

### ISSUE THREAD

**Issue by enekose** [rarible/ethereum-sdk#112]
Is it possible to get an order given an orderId? Thank you.

**Comment by enekose** [comment]
> You can get order by order hash (order id) : sdk.apis.order.getOrderByHash({ hash: orderId })

The order hash is not the same as the order id, is it?

**Comment by ex1st0r** [comment]
hash is the same as the order id

**Comment by enekose** [comment]
> hash is the same as the order id

I thought it wasn't because I was getting id (numeric) and order_hash (alphanumeric), both being different values

I am having issues to initialize the sdk. Can I do it with HDWalletProvider? Whats the most simple way?
