### ISSUE TITLE
Error while create RaribleSDK instance with wallet

### ISSUE THREAD

**Issue by theodufort** [rarible/ethereum-sdk#206]
Im getting an error while trying to create an object instance of a rariblesdk in my TypeScript app file.

Here's the error on build:
![image](https://user-images.githubusercontent.com/111878790/197044317-be804b49-9910-4f0a-981d-fabf9ff87430.png)

**Comment by ex1st0r** [comment]
I think you have mistake in your code. How can I reproduce?
